# Copyright (c) 2024-2025 NVIDIA CORPORATION. All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

"""Defines default lists of object categories based on physical properties.

These lists categorize objects based on characteristics relevant for spatial
analysis tasks, such as determining potential interactions or relationships.
For example, knowing if an object has a discernible 'face' can influence
contextual relationship calculations (e.g., 'in front of'), and knowing if an
object is movable and placeable on a flat surface is crucial for compatibility
checks like 'on top of'.

The lists provided here are defaults and are intended to be user-configurable.
Users can modify these lists directly or replace them based on the specific
object categories present in their datasets or required for their analysis tasks.

Defined Lists:
- `items_with_face`: Objects typically having a primary interaction face.
- `flat_surface_items`: Objects typically providing a flat surface for placement.
- `movable_items`: Objects generally considered movable.
- `movable_and_placeable_items`: A subset of movable items suitable for placing on surfaces.
- `embodiedscan_objs`: A comprehensive list of object categories found in the EmbodiedScan dataset (provided for reference).
"""

# GPT-generated item filter list

items_with_face = [
    'air conditioner', 'alarm', 'album', 'bed', 'bicycle', 'blackboard',
    'book', 'camera', 'car', 'cabinet', 'calendar', 'clock', 'computer',
    'copier', 'couch', 'desk', 'dishwasher', 'door', 'drawer', 'drum',
    'fan', 'fireplace', 'garage door', 'guitar', 'heater', 'humidifier', 'kettle',
    'keyboard', 'laptop', 'mailbox', 'microwave', 'mirror', 'monitor', 'oven',
    'piano', 'picture', 'projector', 'refrigerator', 'screen', 'shelf', 'sink', 'stand',
    'speaker', 'stairs', 'stove', 'tablet', 'telephone', 'tv',
    'toilet', 'vacuum cleaner', 'washing machine', 'window'
]


flat_surface_items = [
    'bar', 'beam', 'bed', 'bench', 'cabinet', 'cart',
    'chair', 'counter', 'countertop', 'crate',
    'cube', 'desk', 'dresser', 'footstool',
    'kitchen island', 'mat', 'mattress', 'ottoman',
    'package', 'panel', 'pedestal', 'pool table',
    'rack', 'rail', 'shelf', 'stand', 'steps', 'stool', 'structure', 'support',
    'table', 'tray', 'vanity', 'windowsill'
]

movable_items = [
    'adhesive tape', 'air conditioner', 'alarm', 'album', 'backpack', 'bag', 'ball',
    'basket', 'beanbag', 'bicycle', 'bin', 'blackboard', 'blanket', 'board',
    'body loofah', 'book', 'boots', 'bottle', 'bowl', 'box', 'bread',
    'broom', 'brush', 'bucket', 'camera', 'can', 'candle', 'candlestick',
    'cap', 'car', 'carpet', 'cart', 'case', 'chair', 'cleanser',
    'clock', 'clothes', 'clothes dryer', 'coat hanger', 'coffee maker', 'commode', 'computer',
    'conducting wire', 'container', 'control', 'copier', 'cosmetics', 'crib', 'cup',
    'curtain', 'cushion', 'decoration', 'desk', 'detergent', 'device', 'dish rack',
    'dispenser', 'divider', 'drawer', 'dress', 'dresser', 'drum', 'dumbbell',
    'dustpan', 'dvd', 'eraser', 'excercise equipment', 'fan', 'file', 'fire extinguisher',
    'flowerpot', 'folder', 'food', 'footstool', 'frame', 'fruit', 'furniture',
    'garbage', 'glass', 'globe', 'glove', 'guitar', 'hair dryer', 'hamper',
    'hat', 'headphones', 'heater', 'helmets', 'holder', 'hook', 'humidifier',
    'jacket', 'jar', 'kettle', 'keyboard', 'kitchenware', 'knife', 'label',
    'ladder', 'lamp', 'laptop', 'letter', 'light', 'luggage', 'machine',
    'magazine', 'mailbox', 'map', 'mask', 'mat', 'mattress', 'menu',
    'microwave', 'mirror', 'mop', 'mouse', 'napkins', 'notebook', 'object',
    'ottoman', 'oven', 'pack', 'package', 'pad', 'pan', 'paper',
    'paper cutter', 'pen', 'pillow', 'pitcher', 'plant', 'plate', 'player',
    'plug', 'plunger', 'pool', 'pool table', 'poster', 'pot', 'price tag',
    'printer', 'projector', 'purse', 'rack', 'radiator', 'radio', 'remote control',
    'roll', 'rope', 'sack', 'salt', 'scale', 'scissors', 'screen',
    'seasoning', 'shampoo', 'sheet', 'shirt', 'shoe', 'shovel', 'sign',
    'soap', 'soap dish', 'soap dispenser', 'speaker', 'sponge', 'spoon', 'stand',
    'stapler', 'statue', 'stick', 'stool', 'sunglasses', 'tablet', 'teapot',
    'telephone', 'tissue', 'tissue box', 'toaster', 'toiletry', 'tool', 'toothbrush',
    'toothpaste', 'towel', 'toy', 'tray', 'treadmill', 'trophy', 'tube',
    'tv', 'umbrella', 'urn', 'utensil', 'vacuum cleaner', 'vase', 'wardrobe',
    'washbasin', 'washing machine', 'wine', 'wrap'
]


movable_and_placeable_items = [
    'adhesive tape',
    'alarm',
    'album',
    'backpack',
    'bag',
    'ball',
    'basket',
    'beanbag',
    'bicycle',
    'bin',
    'blanket',
    'board',
    'body loofah',
    'book',
    'boots',
    'bottle',
    'bowl',
    'box',
    'bread',
    'broom',
    'brush',
    'bucket',
    'calendar',
    'camera',
    'can',
    'candle',
    'candlestick',
    'cap',
    'carpet',
    'cart',
    'case',
    'chair',
    'cleanser',
    'clock',
    'clothes',
    'coat hanger',
    'coffee maker',
    'coil',
    'computer',
    'conducting wire',
    'container',
    'control',
    'cosmetics',
    'crate',
    'cube',
    'cup',
    'curtain',
    'cushion',
    'decoration',
    'detergent',
    'device',
    'dish rack',
    'dispenser',
    'door knob',
    'drawer',
    'dress',
    'drum',
    'dumbbell',
    'dustpan',
    'dvd',
    'eraser',
    'fan',
    'file',
    'fire extinguisher',
    'flowerpot',
    'folder',
    'food',
    'footstool',
    'frame',
    'fruit',
    'garbage',
    'glass',
    'globe',
    'glove',
    'guitar',
    'hair dryer',
    'hamper',
    'hanger',
    'hat',
    'headphones',
    'heater',
    'helmets',
    'holder',
    'hook',
    'humidifier',
    'ironware',
    'jacket',
    'jar',
    'kettle',
    'keyboard',
    'kitchenware',
    'knife',
    'label',
    'ladder',
    'lamp',
    'laptop',
    'letter',
    'light',
    'luggage',
    'magazine',
    'map',
    'mask',
    'mat',
    'menu',
    'microwave',
    'mirror',
    'monitor',
    'mop',
    'mouse',
    'napkins',
    'notebook',
    'object',
    'ottoman',
    'pack',
    'package',
    'pad',
    'pan',
    'paper',
    'paper cutter',
    'pen',
    'picture',
    'pillow',
    'pipe',
    'pitcher',
    'plant',
    'plate',
    'player',
    'plug',
    'plunger',
    'poster',
    'pot',
    'price tag',
    'printer',
    'projector',
    'purse',
    'rack',
    'radio',
    'remote control',
    'rod',
    'roll',
    'rope',
    'sack',
    'salt',
    'scale',
    'scissors',
    'screen',
    'seasoning',
    'shampoo',
    'sheet',
    'shirt',
    'shoe',
    'shovel',
    'sign',
    'soap',
    'soap dish',
    'soap dispenser',
    'speaker',
    'sponge',
    'spoon',
    'stand',
    'stapler',
    'statue',  # if small enough
    'stick',
    'stool',
    'sunglasses',
    'table',   # if small enough
    'tablet',
    'teapot',
    'telephone',
    'tissue',
    'tissue box',
    'toaster',
    'toilet paper',
    'toiletry',
    'tool',
    'toothbrush',
    'toothpaste',
    'towel',
    'toy',
    'tray',
    'trophy',
    'tube',
    'tv',     # most modern sets can be moved by one person
    'umbrella',
    'urn',
    'utensil',
    'vacuum cleaner',
    'vase',
    'wine',
    'wire',
    'wood',
    'wrap'
]



embodiedscan_objs = [
    'adhesive tape', 'air conditioner', 'alarm', 'album', 'arch', 'backpack',
    'bag', 'balcony', 'ball', 'banister', 'bar', 'barricade', 'baseboard',
    'basin', 'basket', 'bathtub', 'beam', 'beanbag', 'bed', 'bench',
    'bicycle', 'bidet', 'bin', 'blackboard', 'blanket', 'blinds', 'board',
    'body loofah', 'book', 'boots', 'bottle', 'bowl', 'box', 'bread',
    'broom', 'brush', 'bucket', 'cabinet', 'calendar', 'camera', 'can',
    'candle', 'candlestick', 'cap', 'car', 'carpet', 'cart', 'case',
    'ceiling', 'chair', 'chandelier', 'cleanser', 'clock', 'clothes', 
    'clothes dryer', 'coat hanger', 'coffee maker', 'coil', 'column', 
    'commode', 'computer', 'conducting wire', 'container', 'control', 
    'copier', 'cosmetics', 'couch', 'counter', 'countertop', 'crate', 
    'crib', 'cube', 'cup', 'curtain', 'cushion', 'decoration', 'desk', 
    'detergent', 'device', 'dish rack', 'dishwasher', 'dispenser', 'divider', 
    'door', 'door knob', 'doorframe', 'doorway', 'drawer', 'dress', 
    'dresser', 'drum', 'duct', 'dumbbell', 'dustpan', 'dvd', 'eraser', 
    'exercise equipment', 'fan', 'faucet', 'fence', 'file', 'fire extinguisher', 
    'fireplace', 'floor', 'flowerpot', 'flush', 'folder', 'food', 'footstool', 
    'frame', 'fruit', 'furniture', 'garage door', 'garbage', 'glass', 'globe', 
    'glove', 'grab bar', 'grass', 'guitar', 'hair dryer', 'hamper', 'handle', 
    'hanger', 'hat', 'headboard', 'headphones', 'heater', 'helmets', 'holder', 
    'hook', 'humidifier', 'ironware', 'jacket', 'jalousie', 'jar', 'kettle', 
    'keyboard', 'kitchen island', 'kitchenware', 'knife', 'label', 'ladder', 
    'lamp', 'laptop', 'ledge', 'letter', 'light', 'luggage', 'machine', 
    'magazine', 'mailbox', 'map', 'mask', 'mat', 'mattress', 'menu', 
    'microwave', 'mirror', 'molding', 'monitor', 'mop', 'mouse', 'napkins', 
    'notebook', 'object', 'ottoman', 'oven', 'pack', 'package', 'pad', 
    'pan', 'panel', 'paper', 'paper cutter', 'partition', 'pedestal', 
    'pen', 'person', 'piano', 'picture', 'pillar', 'pillow', 'pipe', 
    'pitcher', 'plant', 'plate', 'player', 'plug', 'plunger', 'pool', 
    'pool table', 'poster', 'pot', 'price tag', 'printer', 'projector', 
    'purse', 'rack', 'radiator', 'radio', 'rail', 'range hood', 
    'refrigerator', 'remote control', 'ridge', 'rod', 'roll', 'roof', 
    'rope', 'sack', 'salt', 'scale', 'scissors', 'screen', 'seasoning', 
    'shampoo', 'sheet', 'shelf', 'shirt', 'shoe', 'shovel', 'shower', 
    'sign', 'sink', 'soap', 'soap dish', 'soap dispenser', 'socket', 
    'speaker', 'sponge', 'spoon', 'stairs', 'stall', 'stand', 'stapler', 
    'statue', 'steps', 'stick', 'stool', 'stopcock', 'stove', 'structure', 
    'sunglasses', 'support', 'switch', 'table', 'tablet', 'teapot', 
    'telephone', 'thermostat', 'tissue', 'tissue box', 'toaster', 
    'toilet', 'toilet paper', 'toiletry', 'tool', 'toothbrush', 
    'toothpaste', 'towel', 'toy', 'tray', 'treadmill', 'trophy', 'tube', 
    'tv', 'umbrella', 'urn', 'utensil', 'vacuum cleaner', 'vanity', 
    'vase', 'vent', 'ventilation', 'wall', 'wardrobe', 'washbasin', 
    'washing machine', 'water cooler', 'water heater', 'window', 
    'window frame', 'windowsill', 'wine', 'wire', 'wood', 'wrap'
]

